const ProfilPicture: Record<number, string> = {
  1: "/profil-picture/default/bunny.jpg",
  2: "/profil-picture/default/happyBoy.jpg",
  3: "/profil-picture/default/happyEmoji.jpg",
  4: "/profil-picture/default/happyStudent.jpg",
  5: "/profil-picture/default/magicalBear.jpg",
  6: "/profil-picture/default/mathBot.webp",
  7: "/profil-picture/default/schoolBoy.webp",
  8: "/profil-picture/default/simplistProfil.webp",

  9: "/profil-picture/road/scientist.jpg",
  10: "/profil-picture/road/pi.png",
  11: "/profil-picture/road/squareRoot.png",
  12: "/profil-picture/road/pinguin.png",
  13: "/profil-picture/default/bunny.jpg",
  14: "/profil-picture/default/bunny.jpg",
  15: "/profil-picture/default/bunny.jpg",
  16: "/profil-picture/default/bunny.jpg",
  17: "/profil-picture/road/scientistFou.webp",
  18: "/profil-picture/default/bunny.jpg",
  19: "/profil-picture/default/bunny.jpg",
  20: "/profil-picture/default/bunny.jpg",
  21: "/profil-picture/default/bunny.jpg",
  22: "/profil-picture/default/bunny.jpg",
  23: "/profil-picture/default/bunny.jpg",
  24: "/profil-picture/road/universeMaster.webp",
  25: "/profil-picture/default/bunny.jpg",
  26: "/profil-picture/default/bunny.jpg",
  27: "/profil-picture/default/bunny.jpg",
  28: "/profil-picture/road/mathMaster.webp",
  29: "/profil-picture/road/theFirst.jpg",
};

export default ProfilPicture;